In [57]:
from sklearn import preprocessing
import numpy as np
from numpy import genfromtxt
import pandas as pd

#my_data = genfromtxt('training_data_2016.csv', delimiter=',')
#Data = np.asarray(my_data)
#unique=np.unique(column(Data,2))
#print(unique)

Data = pd.read_csv('training_data_2016.csv',low_memory = False)
Data.drop('Policy_Company', 1, inplace=True)
Data.drop('Vehicle_Annual_Miles', 1, inplace=True)
Data.drop('Vehicle_Comprehensive_Coverage_Limit', 1, inplace=True)
Data.drop('Vehicle_Make_Description', 1, inplace=True)
Data.drop('EEA_PolicyYear', 1, inplace=True)
replacements = {
   'Policy_Zip_Code_Garaging_Location': {
      r'Unknown': 0,},
#     'Vehicle_Miles_To_Work': {
#       r'-1': np.nan,},
    'Vehicle_Passive_Restraint': {
      r'Unknown': 'Y',},
#     'Vehicle_Med_Pay_Limit': {
#       r'Unknown': np.nan,},
    'EEA_Policy_Zip_Code_3': {
        r'Unknown':0
    }
}

Data.replace(replacements, regex=True, inplace=True)
categorical_columns = ['Policy_Installment_Term', 'Policy_Billing_Code', 'Policy_Method_Of_Payment', 'Policy_Reinstatement_Fee_Indicator', 'Policy_Zip_Code_Garaging_Location', 'Vehicle_Performance', 'Vehicle_Number_Of_Drivers_Assigned', 'Vehicle_Usage', 'Vehicle_Anti_Theft_Device', 'Vehicle_Passive_Restraint', 'Vehicle_Med_Pay_Limit', 'Vehicle_Bodily_Injury_Limit', 'Vehicle_Physical_Damage_Limit', 'Vehicle_Comprehensive_Coverage_Indicator', 'Vehicle_Comprehensive_Coverage_Limit', 'Vehicle_Collision_Coverage_Indicator', 'Vehicle_Collision_Coverage_Deductible', 'Vehicle_Youthful_Driver_Indicator', 'Vehicle_Youthful_Driver_Training_Code', 'Vehicle_Youthful_Good_Student_Code', 'Vehicle_Safe_Driver_Discount_Indicator', 'EEA_Liability_Coverage_Only_Indicator', 'EEA_Multi_Auto_Policies_Indicator', 'EEA_Policy_Zip_Code_3', 'EEA_Agency_Type', 'EEA_Packaged_Policy_Indicator', 'EEA_Full_Coverage_Indicator', 'EEA_Prior_Bodily_Injury_Limit', 'SYS_Renewed', 'SYS_New_Business']

for col in Data[1:]:
    if col in categorical_columns:
        Data[col] = Data[col].astype('category')
#     print (Data[col].unique())
#     print Data[col].columns
#print Data[1].unique()
#print list(Data.columns.values)
#print(Data.head())
cat_columns = Data.select_dtypes(['category']).columns
Data[cat_columns] = Data[cat_columns].apply(lambda x: x.cat.codes)


In [58]:
# print (Data[1:])
# print (Data.columns.values)
print(Data.values[0,:])

[  0.00000000e+00   0.00000000e+00   1.00000000e+00   0.00000000e+00
   7.15000000e+02   3.50000000e+01   2.00400000e+03   4.00000000e+00
  -1.00000000e+00   1.10000000e+01   0.00000000e+00   1.00000000e+00
  -1.00000000e+00   5.00000000e+00   2.00000000e+00   1.00000000e+00
   3.00000000e+00   1.00000000e+00   4.00000000e+00   4.00000000e+00
   0.00000000e+00   1.00000000e+00   5.00000000e+00   1.00000000e+00
   0.00000000e+00   1.00000000e+00   0.00000000e+00   0.00000000e+00
   1.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00
   7.50000000e+01   7.50000000e+01   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   1.00000000e+00   0.00000000e+00   0.00000000e+00
   1.00000000e+00   0.00000000e+00   1.00000000e+00   0.00000000e+00
   0.00000000e+00   7.30000000e+01   2.27000000e+01   3.00000000e+00
   0.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
   0.00000000e+00   3.20120000e+02

In [63]:
# Feature Extraction with Univariate Statistical Tests (Chi-squared for classification)
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression
# load data

array = Data.values
print(array.shape)

X = array[:,0:-5]
print (X.shape)
Y = array[:,-1]
print (Y.shape)
# feature extraction
test = SelectKBest(score_func=f_regression, k=4)
fit = test.fit(X, Y)
# summarize scores
np.set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
is_feature_rel = fit.get_support()
rel_names = [Data.columns.values[i] for i in range(X.shape[1]) if is_feature_rel[i]]

print(rel_names)
print(features)

(424431, 63)
(424431, 58)
(424431,)
[  1.247e-03   4.227e-01   4.339e-01   2.919e-01   1.629e+00   4.638e+00
   2.065e+00   1.043e+01   1.032e-01   5.971e-01   2.579e+00   1.343e+00
   4.832e-01   9.560e-06   8.710e-02   2.376e+00   1.694e+00   4.502e-01
   2.527e-01   4.470e-01   6.300e-01   4.581e-02   1.054e-01   1.410e+01
   1.856e-02   6.274e+00   2.336e+00   1.804e-01   8.398e-02   2.017e+00
   6.662e+00   1.394e+01   8.702e-01   2.743e-01   1.203e+01   1.113e+00
   8.648e-01   9.219e-01   2.209e-01   2.344e+00   3.046e+01   2.866e-01
   9.581e+00   1.237e+01   5.145e+00   1.455e+00   8.754e+00   3.345e-03
   3.122e-01   5.260e-01   2.843e+00   1.845e-02   4.489e-01   8.106e-02
   7.597e-03   3.306e+02   2.899e+00   7.554e+01]
['Driver_Total', 'Driver_Total_Senior_Ages_65_69', 'SYS_Renewed', 'Annual_Premium']
[[   1.      0.      1.    320.12]
 [   1.      0.      1.    259.7 ]
 [   1.      0.      1.    613.74]
 ..., 
 [   1.      0.      0.    118.21]
 [   1.      0.      0.   